### ISSUE TITLE
Opening a file that is bigger than 10% of RAM memory will fill the /run/user/xxxx directory without a warning.

### ISSUE THREAD

**Issue by Hell01World** [flathub/net.sourceforge.mcomix#19]
https://github.com/flathub/net.sourceforge.mcomix/assets/110909985/8dc3356e-c6ea-4797-9ed5-d8d4f3e18120

Distribution: Debian 12 with stable repo

With no space left in this directory, I cannot open any other flatpak application such as Firefox because it's going to return an error that it cannot write into /run/user/xxxx

**Comment by Hell01World** [comment]
Now I realized that even MComix from apt writes huge amount of data to some kind of directory, which is extremely bad for a SSD.

![image](https://github.com/flathub/net.sourceforge.mcomix/assets/110909985/f74d5996-a222-428d-8325-0ea10d622dd9)

**Comment by catsout** [comment]
Fixed, will not use ram.
